- hosts: localhost
  vars:
    source_key: "./.ssh/kochnev.tech"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/kochnev.tech"
  tasks:
   - include_tasks: tasks/ssh.yml
   - include_tasks: tasks/zsh.yml
   - include_tasks: tasks/git.yml
   - include_tasks: tasks/nvim.yml
   - include_tasks: tasks/dotfiles.yml
